name: Link PAL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Kind'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Test
          - PreProd
          - Prod
      partnerId:
        description: 'Partner ID'
        required: true
        default: '1699614'

env:
  Dev: my-service-connection-dev
  Test: my-service-connection-qa
  PreProd: my-service-connection-pre-prod
  Prod: my-service-connection-prod

jobs:
  RunCommand:
    name: Run az cli to register
    runs-on: ${{ inputs.environment == 'Prod' || inputs.environment == 'PreProd' && 'ubuntu-22.04' || 'ubuntu-latest' }}

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env[inputs.environment]] }}

      - name: Run az managementpartner create
        run: |
          echo "Running az managementpartner create --partner-id ${{ inputs.partnerId }}"
          az managementpartner create --partner-id ${{ inputs.partnerId }}
